[project]
name = "tfm-proyecto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.3.0",
    "pymongo[srv]>=4.13.2",
    "python-dotenv>=1.1.1",
    "tqdm>=4.67.1",
]
